version: '2'
services:
    saeon_geoserver:
        build:
            context: ./geoserver-docker
            dockerfile: Dockerfile

        container_name: saeon_geoserver

        volumes:
            #- ./webapps/:/usr/local/tomcat/webapps/
            - ./geoserver-data/:/opt/

        ports:
            - "8080:8080"       
        
        #restart: always
    postgres:
        #image: postgres:9.6
        build:
            context: ./postgis-docker
            dockerfile: Dockerfile
        container_name: saeon_postgres
        ports:
            - "5432:5432"

        volumes:
            - ./data/:/var/lib/postgresql/data
            - /mnt/media/postgres_dump_app01/2019_MIGRATION/:/opt/
        #restart: always

