version: '2'
services:
    saeon_geoserver_0:
        build:
            context: ./geoserver-docker
            dockerfile: Dockerfile

        container_name: saeon_geoserver_0

        environment:
            - MINMEM=512M
            - MAXMEM=2G

        volumes:
            #- ./webapps/:/usr/local/tomcat/webapps/
            #- ./geoserver-data/:/opt/
            #- /mnt/media/geoservers_app01/Instance5Bkp/:/opt/

            - ./geoserver-docker/setenv.sh:/usr/local/tomcat/bin/setenv.sh:ro
            - ./geoserver-logs/:/usr/local/tomcat/logs/

            - /mnt/media2/geoservers_app01/restructured/spatial-data/instance_0/:/mnt/data_dir/
            - /mnt/media2/geoservers_app01/restructured/geoserver-config/instance_0/:/opt/config_dir/

        ports:
            - "8080:8080"
      
        #restart: always


    saeon_geoserver_1:
        build:
            context: ./geoserver-docker
            dockerfile: Dockerfile

        container_name: saeon_geoserver_1

        environment:
            - MINMEM=512M
            - MAXMEM=2G

        volumes:
            #- ./webapps/:/usr/local/tomcat/webapps/
            #- ./geoserver-data/:/opt/
            #- /mnt/media/geoservers_app01/Instance5Bkp/:/opt/

            - ./geoserver-docker/setenv.sh:/usr/local/tomcat/bin/setenv.sh:ro
            - ./geoserver-logs/:/usr/local/tomcat/logs/

            - /mnt/media2/geoservers_app01/restructured/spatial-data/instance_1/:/mnt/data_dir/
            - /mnt/media2/geoservers_app01/restructured/geoserver-config/instance_1/:/opt/config_dir/

        ports:
            - "8081:8080"

        #restart: always

    saeon_geoserver_2:
        build:
            context: ./geoserver-docker
            dockerfile: Dockerfile

        container_name: saeon_geoserver_2

        environment:
            - MINMEM=512M
            - MAXMEM=2G

        volumes:
            #- ./webapps/:/usr/local/tomcat/webapps/
            #- ./geoserver-data/:/opt/
            #- /mnt/media/geoservers_app01/Instance5Bkp/:/opt/

            - ./geoserver-docker/setenv.sh:/usr/local/tomcat/bin/setenv.sh:ro
            - ./geoserver-logs/:/usr/local/tomcat/logs/

            - /mnt/media2/geoservers_app01/restructured/spatial-data/instance_2/:/mnt/data_dir/
            - /mnt/media2/geoservers_app01/restructured/geoserver-config/instance_2/:/opt/config_dir/

        ports:
            - "8082:8080"

        #restart: always

    saeon_geoserver_3:
        build:
            context: ./geoserver-docker
            dockerfile: Dockerfile

        container_name: saeon_geoserver_3

        environment:
            - MINMEM=512M
            - MAXMEM=2G

        volumes:
            #- ./webapps/:/usr/local/tomcat/webapps/
            #- ./geoserver-data/:/opt/
            #- /mnt/media/geoservers_app01/Instance5Bkp/:/opt/

            - ./geoserver-docker/setenv.sh:/usr/local/tomcat/bin/setenv.sh:ro
            - ./geoserver-logs/:/usr/local/tomcat/logs/

            - /mnt/media2/geoservers_app01/restructured/spatial-data/instance_3/:/mnt/data_dir/
            - /mnt/media2/geoservers_app01/restructured/geoserver-config/instance_3/:/opt/config_dir/

        ports:
            - "8083:8080"

        #restart: always


