version: '2'
services:
    postgres:
        #image: postgres:9.6
        build:
            context: ./postgis-docker
            dockerfile: Dockerfile
        container_name: saeon_postgres
        ports:
            - "5432:5432"

        volumes:
            - ./data/:/var/lib/postgresql/data
            - /mnt/spatial-data/postgres-database-backups/:/opt/
            - ./utils/:/scripts/
        #restart: always

