version: '2'
services:
    saeon_geoserver:
        build:
            context: ./geoserver-docker
            dockerfile: Dockerfile

        container_name: saeon_geoserver

        environment:
            - MINMEM=512M
            - MAXMEM=2G

        volumes:
            #- ./webapps/:/usr/local/tomcat/webapps/
            - ./geoserver-data/:/opt/
            #- /mnt/media/geoservers_app01/Instance5Bkp/:/opt/

            - ./geoserver-docker/setenv.sh:/usr/local/tomcat/bin/setenv.sh:ro
            - ./geoserver-logs/:/usr/local/tomcat/logs/

        ports:
            - "8080:8080"

        links:
            - postgres

        depends_on:
            - postgres
        
        #restart: always
    postgres:
        #image: postgres:9.6
        build:
            context: ./postgis-docker
            dockerfile: Dockerfile
        container_name: saeon_postgres
        ports:
            - "5432:5432"

        volumes:
            - ./data/:/var/lib/postgresql/data
            - /mnt/media/postgres_dump_app01/2019_MIGRATION/:/opt/
            - ./utils/:/scripts/
        #restart: always

